### PR TITLE
Lot's of changes and improvements

### PR DESCRIPTION
**Pull request by Luapulu**
This contains

- More comprehensive suite of tests (150+ tests total)
- Fix for #5
- Can get instant velocity and instant charge
- Support for bottom bullet radius
- Allows selectively applying self repulsion and acceleration effects (tests needed)
- Rename `Struct_MJD_Siggen_Setup` to `SigGenSetup`
- Overload `getproperty`, rather than defining special accessor functions
- Export certain functions and 'SigGenSetup' so as to define user interface more clearly
- Added `with_coll_effects!` and `coll_effects_off!` (Implements #7)
- Still need documentation
- Would like to add some convenience methods

### CODE REVIEW

**Comment by oschulz** [comment]
Thanks! Let me quickly update the package to use GitHub CI to run tests.

**Comment by oschulz** [comment]
Actually, I guess I better merge this first, for Project.toml, etc.

**Comment by oschulz** [comment]
Oh, sorry, just saw the (WIP) label - @Luapulu , let me know when this is ready to merge from your side?

**Comment by Luapulu** [comment]
Ok, @oschulz, my stuff is good to merge as far as I'm concerned. I haven't touched @TComellato's changes, so we don't have tests for any of those yet. (His changes are mostly about being able to separate the different collective effects if I understand correctly)

I think I'll make the ci changes we talked about. (Add docs template, switch to github workflow and bring this Project.toml in line with #6). Then we should be good to merge, I think.

**Comment by oschulz** [comment]
Hm, why isn't GitHub ci running?

**Comment by oschulz** [comment]
Shouldn't be necessary for the workflow files to be on master to enable the workflows.

**Comment by oschulz** [comment]
I think I have to merge it before the workflows get enabled. So I'll merge it now, and then we can to fixes in a separate PR.

**Pull request merged**
