### PR TITLE
Replace REQUIRE with Project.toml and fix .travis.yml

### PR DESCRIPTION
**Pull request by Luapulu**
I added Manifest.toml to the .gitignore. I'm not sure if you want that. Otherwise, it's pretty straightforward.

### CODE REVIEW

**Comment by oschulz** [comment]
> I added Manifest.toml to the .gitignore. I'm not sure if you want that.

Yes, please!

One question, which UUID did you use in Project.toml?

**Comment by Luapulu** [comment]
I'm pretty sure I used `UUIDs.uuid4()` to generate a new uuid.

**Comment by oschulz** [comment]
Let's use

```
uuid = "0b925020-e659-485c-98dd-189633cb4be4"
```

**Comment by Luapulu** [comment]
Done. I don't understand why the travis CI build fails eventhough the tests pass. 🤔

**Comment by Luapulu** [comment]
If you consider this package a work in progress, we may also want to set the version to 0.0.1 instead of 0.1.0 Apparently julia convention goes against semantic versioning and only considers 0.0.* to be incompatible. As of 0.1.0, minor versions are expected to be compatible with previous versions.

**Comment by Luapulu** [comment]
Another thought: do you want to be added as an author in the Project.toml? Should the authors of the original siggen code be added, too?

**Comment by oschulz** [comment]
> Another thought: do you want to be added as an author in the Project.toml?

No, I tend to keep Project.toml purely technical.

**Comment by oschulz** [comment]
> If you consider this package a work in progress, we may also want to set the version

Make it version 0.1. We can always count up when we do breaking changes. :-)

**Comment by oschulz** [comment]
> Done. I don't understand why the travis CI build fails eventhough the tests pass.

Maybe best to require Julia v1.3, and run tests on v1.3, v1.5 and nightly. See here for a more up-to-date Julia Travis config:

https://github.com/oschulz/ValueShapes.jl/blob/master/.travis.yml

**Comment by Luapulu** [comment]
It doesn't like that `Pkg.build` is being called with `verbose=true` 🤔

**Comment by Luapulu** [comment]
Jup, removing the verbose keyword did it. 😊

**Comment by Luapulu** [comment]
Should be ready to merge now.

**Comment by oschulz** [comment]
Thanks!!

**Pull request merged**
