### PR TITLE
Add basic usage section to docs

### PR DESCRIPTION
**Pull request by Luapulu**
Should we set the README to be the home page of the docs page?

### CODE REVIEW

**Comment by Luapulu** [comment]
This would complete one part of #10

**Comment by oschulz** [comment]
> Should we set the README to be the home page of the docs page

No, the current convention in the Julia community is to have a short description of the package in the README, and the in-depth description in the docs (in "docs/src/index.md", or a deeper structure for complex packages), since test in the docs can easily link to the API docs.

**Comment by Luapulu** [comment]
One link is broken, let me fix it before we merge.

**Comment by Luapulu** [comment]
Good to merge now if you have no objection @oschulz.

**Comment by oschulz** [comment]
Why don't we move most of this to "docs/src/index.md"?

**Comment by Luapulu** [comment]
I can do that. You're thinking of moving the whole basic usage section, or do you want some simplified version to stay in the README?

**Comment by Luapulu** [comment]
Should be good now?

**Comment by oschulz** [comment]
Looks good! :-)

**Pull request merged**
